# Generated by Django 5.2.1 on 2025-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('guest_count', models.IntegerField()),
                ('reservation_time', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
