# Generated by Django 5.2.1 on 2025-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
