# Generated by Django 5.2.1 on 2025-05-14 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_reservation_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=datetime.date(2025, 5, 14)),
            preserve_default=False,
        ),
    ]
