# Generated by Django 5.2.1 on 2025-05-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_reservation_reservation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPFStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('limitado', 'Limitado (2 reservas / 15 dias)'), ('livre', 'Livre (Reservas ilimitadas)'), ('bloqueado', 'Bloqueado (1 por semana)'), ('inativo', 'Inativo')], default='novo', max_length=20)),
                ('ultima_reserva', models.DateField(blank=True, null=True)),
                ('data_bloqueio', models.DateField(blank=True, null=True)),
                ('data_desbloqueio', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
